name: doc_app
description: Image to PDF AI App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.1
  google_fonts: ^6.2.1
  pdf: ^3.11.1
  printing: ^5.13.2

flutter:
  uses-material-design: true
